#!/bin/bash

if [ "$0" = "alxgit" ]; then
  shift
fi

if [ $# -lt 1 ]; then
  echo "Usage: $0 <commit_message> [<branch_name>]"
   echo "OR"
  echo "Usage: alxgit <commit_message> <branch_name>"
  exit 1
fi

commit_message="$1"

if [ $# -ge 2 ]; then
	branch_name="$2"
	git add .
	git commit -m "$commit_message"
	git push origin "$branch_name"
	echo "Committing to github with message : $commit_message on branch_name : $branch_name"
else
	git add .
	echo "Committing to github with message : $commit_message"
	git commit -m "$commit_message"
	git push
fi