#!/bin/bash
# FoNiX - ALX Advanced GitHub Push : https://github.com/FoNiXPr020/alx-advanced_github

chmod +x $0

source_file="github"
destination_dir="C:/Github/"

if [ ! -d "$destination_dir" ]; then
  mkdir -p "$destination_dir"
  echo "Created directory: $destination_dir"
fi

cp "$source_file" "$destination_dir"

alias_to_add="alias alxgit='C:/Github/./github'"

if grep -q "$alias_to_add" ~/.bashrc || grep -q "$alias_to_add" ~/.bash_aliases; then
  echo "Alias 'alxgit' already exists in ~/.bashrc or ~/.bash_aliases."
else
  if [ -f ~/.bash_aliases ]; then
    echo "Adding alias to ~/.bash_aliases..."
    echo "$alias_to_add" >> ~/.bash_aliases
  else
    echo "Adding alias to ~/.bashrc..."
    echo "$alias_to_add" >> ~/.bashrc
  fi
  echo "Alias added successfully."
fi

echo "Installation completed."
